defaults:
    input: 'removables'
    output: 'I:\Family\Sony RX100 IV\'
    # output: /Users/matthew/temp/out
    extensions: ["JPG", "jpg", "png", "mp4", "3gp", "MP4"]
    exclusions: ["WA",]
    log: media-worker.log
    verbose: False
    foldernames: date # date | location
    method: copy # copy | move
