defaults:
    # "input": r"I:\Family\Sony RX100 IV\input"
    # input: D:\etc\media_sorter_test\in
    input: /Users/matthew/temp/in
    # output: r"I:\Family\Sony RX100 IV\output"
    # output: D:\etc\media_sorter_test\out
    output: /Users/matthew/temp/out
    extensions: ["JPG", "jpg", "png", "mp4", "3gp", "MP4"]
    exclusions: ["WA",]
    # log: r"I:\Family\Sony RX100 IV\output\media-worker.log"
    log: /Users/matthew/temp/worker.log
    verbose: False
    foldernames: date
    # foldernames: location
