defaults:
    # "input": r"I:\Family\Sony RX100 IV\input"
    # input: D:\etc\media_sorter_test\in
    # input: /Users/matthew/temp/in
    input: 'C:\temp\photos\'
    # input: 'removables'
    # output: 'I:\Family\Sony RX100 IV'
    output: 'I:\Matthew\photos\0 Cellphone\'
    # output: D:\etc\media_sorter_test\out
    # output: /Users/matthew/temp/out
    extensions: ["JPG", "jpg", "png", "mp4", "3gp", "MP4"]
    exclusions: ["WA",]
    log: 'media-worker.log'
    # log: /Users/matthew/temp/worker.log
    verbose: False
    foldernames: date
    # foldernames: location
    method: 'copy' # 'copy' | 'move'
